# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Userid(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, phone_number: str=None, user_name: str=None, email_id: str=None, password: str=None):  # noqa: E501
        """Userid - a model defined in Swagger

        :param phone_number: The phone_number of this Userid.  # noqa: E501
        :type phone_number: str
        :param user_name: The user_name of this Userid.  # noqa: E501
        :type user_name: str
        :param email_id: The email_id of this Userid.  # noqa: E501
        :type email_id: str
        :param password: The password of this Userid.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'phone_number': str,
            'user_name': str,
            'email_id': str,
            'password': str
        }

        self.attribute_map = {
            'phone_number': 'phone number',
            'user_name': 'user name',
            'email_id': 'email id',
            'password': 'password'
        }
        self._phone_number = phone_number
        self._user_name = user_name
        self._email_id = email_id
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'Userid':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The userid of this Userid.  # noqa: E501
        :rtype: Userid
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this Userid.


        :return: The phone_number of this Userid.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this Userid.


        :param phone_number: The phone_number of this Userid.
        :type phone_number: str
        """

        self._phone_number = phone_number

    @property
    def user_name(self) -> str:
        """Gets the user_name of this Userid.


        :return: The user_name of this Userid.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name: str):
        """Sets the user_name of this Userid.


        :param user_name: The user_name of this Userid.
        :type user_name: str
        """

        self._user_name = user_name

    @property
    def email_id(self) -> str:
        """Gets the email_id of this Userid.


        :return: The email_id of this Userid.
        :rtype: str
        """
        return self._email_id

    @email_id.setter
    def email_id(self, email_id: str):
        """Sets the email_id of this Userid.


        :param email_id: The email_id of this Userid.
        :type email_id: str
        """

        self._email_id = email_id

    @property
    def password(self) -> str:
        """Gets the password of this Userid.


        :return: The password of this Userid.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this Userid.


        :param password: The password of this Userid.
        :type password: str
        """

        self._password = password
