# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Userid2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, home_address: str=None, work_address: str=None, other_address: str=None):  # noqa: E501
        """Userid2 - a model defined in Swagger

        :param home_address: The home_address of this Userid2.  # noqa: E501
        :type home_address: str
        :param work_address: The work_address of this Userid2.  # noqa: E501
        :type work_address: str
        :param other_address: The other_address of this Userid2.  # noqa: E501
        :type other_address: str
        """
        self.swagger_types = {
            'home_address': str,
            'work_address': str,
            'other_address': str
        }

        self.attribute_map = {
            'home_address': 'home-address',
            'work_address': 'work-address',
            'other_address': 'other-address'
        }
        self._home_address = home_address
        self._work_address = work_address
        self._other_address = other_address

    @classmethod
    def from_dict(cls, dikt) -> 'Userid2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The userid_2 of this Userid2.  # noqa: E501
        :rtype: Userid2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def home_address(self) -> str:
        """Gets the home_address of this Userid2.


        :return: The home_address of this Userid2.
        :rtype: str
        """
        return self._home_address

    @home_address.setter
    def home_address(self, home_address: str):
        """Sets the home_address of this Userid2.


        :param home_address: The home_address of this Userid2.
        :type home_address: str
        """

        self._home_address = home_address

    @property
    def work_address(self) -> str:
        """Gets the work_address of this Userid2.


        :return: The work_address of this Userid2.
        :rtype: str
        """
        return self._work_address

    @work_address.setter
    def work_address(self, work_address: str):
        """Sets the work_address of this Userid2.


        :param work_address: The work_address of this Userid2.
        :type work_address: str
        """

        self._work_address = work_address

    @property
    def other_address(self) -> str:
        """Gets the other_address of this Userid2.


        :return: The other_address of this Userid2.
        :rtype: str
        """
        return self._other_address

    @other_address.setter
    def other_address(self, other_address: str):
        """Sets the other_address of this Userid2.


        :param other_address: The other_address of this Userid2.
        :type other_address: str
        """

        self._other_address = other_address
