# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11.3

    # working_directory: ~/app

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv circleci_venv
            . circleci_venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . circleci_venv/bin/activate
            # flake8 --exclude=venv* --statistics
            cd app
            make test